version: '3.9'
services:
  php:
    image: php:8.0-fpm
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/html/src
      - ./config:/var/www/html/config
    environment:
      ENV: "development"
    depends_on:
      - db
    networks:
      - app_net
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: techsupportdb
      MYSQL_USER: tsuser
      MYSQL_PASSWORD: tssecurepass
      MYSQL_ROOT_PASSWORD: tssecurepass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
    networks:
      - app_net

volumes:
  db_data:
networks:
  app_net:
