apiVersion: apps/v1
kind: Deployment
metadata:
  name: techsupport-app
  namespace: techsupport-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: techsupport-app
  template:
    metadata:
      labels:
        app: techsupport-app
    spec:
      containers:
      - name: php
        image: php:8.0-fpm
        ports:
        - containerPort: 9000
        env:
        - name: ENV
          value: "production"
        volumeMounts:
        - name: html
          mountPath: /var/www/html
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /var/www/html
      volumes:
      - name: html
        hostPath:
          path: /home/harry/techsupport_website/public
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: techsupport-service
  namespace: techsupport-ns
spec:
  type: NodePort
  selector:
    app: techsupport-app
  ports:
  - port: 80
    targetPort: 80
